---
title: Astro Pi Flight Data Analysis
hero_image: images/banner.png
description: Do strange, unexplained things happen on the International Space Station?
original_url: https://raspberrypi.org/learning/astro-pi-flight-data-analysis
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: space
technologies: ''
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: What you will need
- title: Astro Pi Flight Data Analysis
- title: What are CSV files?
- title: What's in the CSV files?
- title: Where can I get the CSV files?
- title: How do I analyse the data?
- title: What to look for
- title: What to do when you find something
- title: What next?